apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 227255202149.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 227255202149.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 6fda2e33
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
